# Generated by Django 5.0.3 on 2024-03-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('form_type', models.CharField(max_length=30)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
