# Generated by Django 5.0.3 on 2024-03-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='full_form_type',
            field=models.CharField(default='N', max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_type',
            field=models.CharField(max_length=200),
        ),
    ]
