# Generated by Django 5.0.3 on 2024-03-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentMap', '0002_form_full_form_type_alter_form_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='full_company',
            field=models.CharField(default='N', max_length=200),
        ),
    ]
