# Generated by Django 5.0.3 on 2024-03-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentMap', '0003_form_full_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.CharField(default='None', max_length=4),
        ),
    ]
