# Generated by Django 5.0.3 on 2024-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentMap', '0005_agent_licensedstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedstate',
            name='expiration',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='licensedstate',
            name='licenseNumber',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
